---
namespace: community
name: webapp-role
version: 1.0.0
readme: README.md
authors:
  - Amélie NIOCHE
description: Install webapp
license_file: COPYING
tags:
  - V1
repository: https://github.com/Chatbrume/webapp_role.git
documentation: https://github.com/Chatbrume/webapp_role.git
homepage: https://github.com/Chatbrume/webapp_role.git
issues: https://github.com/Chatbrume/webapp_role.git
build_ignore:
  - .gitignore