- name: create webapp files
  file:
    path: "/home/{{ ansible_user }}/{{ instance.site_name }}"
    state: directory

- name: download git repo
  git:
    repo: 'https://github.com/diranetafen/static-website-example.git'
    dest: /home/{{ ansible_user }}/{{ instance.site_name }}

- name: Copy index template with variable
  template: 		
    src: index.html.j2
    dest: /home/{{ ansible_user }}/{{ instance_1.site_name }}/index.html

- name: "launch docker container"
  docker_container:
    name: "{{ instance.site_name }}"
    image: httpd
    ports: 
      - "{{ instance.port }}:80"
    volumes:
      - /home/{{ ansible_user }}/{{ instance.site_name }}/:/usr/local/apache2/htdocs/:rw
